---

version: 1

disable_existing_loggers: False

formatters:

    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    whole:
        format: "%(asctime)s - %(levelname)s - %(funcName)s - %(lineno)s  - %(thread)d - %(threadName)s - %(message)s"
#        format: "%(asctime)s - %(pathname)s - %(levelname)s - %(funcName)s - %(lineno)s - %(thread)d - %(threadName)s - %(message)s"


handlers:

    console:

        class: logging.StreamHandler

        level: DEBUG

        formatter: whole

        stream: ext://sys.stdout


    info_file_handler:

        class: logging.handlers.TimedRotatingFileHandler

        level: INFO

        formatter: whole

        when: D

        filename: logs/info.log

        backupCount: 8

        encoding: utf8


    error_file_handler:

        class: logging.handlers.TimedRotatingFileHandler

        level: WARNING

        formatter: whole

        when: D

        filename: logs/errors.log

        backupCount: 8

        encoding: utf8


loggers:

    my_module:

        level: ERROR

        handlers: [console]

        propagate: no


root:

#    level: DEBUG
    level: INFO

    handlers: [console, info_file_handler, error_file_handler]